name: flutter_rental_system
description: "A Flutter project for managing rentals."
# Prevent accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.0

  # Additional dependencies
  cupertino_icons: ^1.0.8
  provider: ^6.1.2 # Downgraded to match resolvable versions
  shared_preferences: ^2.3.3 # Updated to latest compatible version
  http: ^1.2.2 # Updated to the latest compatible version
  intl: ^0.20.1 # Updated to the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  async: ^2.12.0
  boolean_selector: ^2.1.2
  characters: ^1.3.1
  clock: ^1.1.2
  collection: ^1.19.1
  fake_async: ^1.3.2
  http_parser: ^4.1.1
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  matcher: ^0.12.17
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  path: ^1.9.1
  stack_trace: ^1.12.0
  string_scanner: ^1.4.0
  test_api: ^0.7.4
  vm_service: ^15.0.0

flutter:
  uses-material-design: true

